### ISSUE TITLE
WAAppRouterParametersProtocol wrong optional "- (NSDictionary*) mappingPropertyKey"

### ISSUE THREAD

**Issue by orgmir** [Wasappli/WAAppRouting#9]
In the `WAAppRouterParametersProtocol` there is an optional method declared 
`- (NSDictionary*) mappingPropertyKey`
I think it got switch around, because the assert in WAAppLinkParameters looks for the override of the `mappingKeyProperty` property.

I don't know which one is switched, but the protocol and the assert should be the same, no?

**Comment by ipodishima** [comment]
Hi

Sorry for the delay about the response. Had some personal events lately ;)

Well yeah, it is optional. In fact, you can see two uses of this protocol: one on mutable dictionary and one on `WAAppLinkParameters`. For the second one, it's needed to get a mapping between your properties and the url parameters. So the assert is right ;)
`WAAppLinkParameters` is intended to be subclassed, that's why there is the assert. Otherwise, use a simple dictionary

**Comment by orgmir** [comment]
Thank you for the response, you are right of course. I should have explained better my problem, since I can't remember why did I post this! I was trying to use `WAPPLinkParameters` and got lost in the code I guess, but everything is working wonderfully now.

Thank you again and I'm closing this one :)
